const PINYIN_GROUPS: Array<[string, string]> = [
  ['a', '阿啊'],
  ['an', '安按案暗岸'],
  ['ao', '奥澳'],
  ['ba', '八巴把坝霸'],
  ['bai', '白百败'],
  ['ban', '版板班办半伴'],
  ['bang', '帮榜邦'],
  ['bao', '包保宝报备堡'],
  ['bei', '北备背贝杯'],
  ['ben', '本奔'],
  ['beng', '崩'],
  ['bi', '比笔必币闭毕壁'],
  ['bian', '边变编便'],
  ['biao', '标表'],
  ['bie', '别'],
  ['bin', '宾滨'],
  ['bing', '并病兵冰'],
  ['bo', '播波博伯'],
  ['bu', '不部布步补'],
  ['cai', '才财采材菜'],
  ['cang', '仓藏'],
  ['ce', '测策侧'],
  ['ceng', '层'],
  ['cha', '查差插'],
  ['chai', '拆'],
  ['chan', '产单禅'],
  ['chang', '长常场厂昌'],
  ['chao', '超朝'],
  ['che', '车撤'],
  ['cheng', '成城程承称'],
  ['chi', '持池迟'],
  ['chong', '冲充重'],
  ['chu', '出处储初'],
  ['chuan', '传串川'],
  ['chuang', '创窗床'],
  ['ci', '次词'],
  ['cong', '从丛'],
  ['cun', '存村'],
  ['cuo', '错'],
  ['da', '大达打答'],
  ['dai', '代带待贷'],
  ['dan', '单担弹丹'],
  ['dao', '到道导岛'],
  ['de', '的德得'],
  ['deng', '登等灯'],
  ['di', '地第低递底'],
  ['dian', '点电典店'],
  ['diao', '调掉'],
  ['ding', '定顶订丁'],
  ['dong', '东动洞冻'],
  ['du', '读独度都'],
  ['duan', '端段断短'],
  ['dui', '队对'],
  ['duo', '多朵'],
  ['e', '额俄'],
  ['er', '二儿'],
  ['fa', '发法罚'],
  ['fan', '反返范饭'],
  ['fang', '方防访房'],
  ['fei', '非费飞'],
  ['fen', '分份粉'],
  ['feng', '风丰峰封'],
  ['fu', '服付复副府负'],
  ['gan', '干感敢'],
  ['gang', '港钢岗'],
  ['gao', '高告稿'],
  ['ge', '个各格隔歌'],
  ['gen', '根跟'],
  ['geng', '更耕'],
  ['gong', '公共工攻供'],
  ['guan', '关管观馆'],
  ['guang', '广光'],
  ['gui', '归规柜'],
  ['guo', '国过果'],
  ['hai', '海还'],
  ['hang', '航行杭'],
  ['hao', '好号毫'],
  ['he', '和核合河'],
  ['hei', '黑'],
  ['hou', '后候'],
  ['hu', '湖户互护'],
  ['hua', '华化话'],
  ['huan', '环换缓'],
  ['huang', '黄'],
  ['hui', '回会汇灰'],
  ['ji', '机级集及计记基即'],
  ['jia', '加家价架佳'],
  ['jian', '件建检监间简键'],
  ['jiang', '江降讲奖'],
  ['jiao', '交脚教角'],
  ['jie', '节结接街界介'],
  ['jin', '进金近紧'],
  ['jing', '京经精镜警'],
  ['jiu', '九久旧'],
  ['ju', '据局具居聚'],
  ['kai', '开凯'],
  ['kan', '看控'],
  ['ke', '客可科课'],
  ['kong', '控空'],
  ['kou', '口扣'],
  ['ku', '库酷'],
  ['kuai', '快块'],
  ['lan', '蓝栏览'],
  ['li', '里理离立例历力'],
  ['lian', '连联链练'],
  ['liang', '量良亮'],
  ['lin', '临林邻'],
  ['liu', '流六留'],
  ['long', '龙'],
  ['lu', '路录陆'],
  ['ma', '码马'],
  ['mai', '买卖'],
  ['man', '满慢'],
  ['mao', '猫贸'],
  ['men', '门'],
  ['mi', '密秘'],
  ['mian', '面免'],
  ['ming', '名明命'],
  ['mo', '模末默'],
  ['mu', '目木'],
  ['na', '拿纳'],
  ['nan', '南难'],
  ['nei', '内'],
  ['neng', '能'],
  ['ni', '你尼'],
  ['nian', '年'],
  ['niu', '牛'],
  ['nuo', '诺'],
  ['ou', '欧'],
  ['pai', '排牌'],
  ['pan', '盘判'],
  ['pei', '配培'],
  ['pi', '批皮'],
  ['pian', '片篇'],
  ['pin', '品频拼'],
  ['ping', '平屏评'],
  ['pu', '普浦'],
  ['qi', '器期其起企七'],
  ['qian', '前签迁钱'],
  ['qiang', '强墙'],
  ['qiao', '桥巧'],
  ['qing', '青清轻情'],
  ['qu', '区取去渠'],
  ['quan', '全权券'],
  ['qun', '群'],
  ['ran', '然'],
  ['re', '热'],
  ['ren', '人认任'],
  ['ri', '日'],
  ['rong', '容融'],
  ['ru', '入如'],
  ['ruan', '软'],
  ['san', '三散'],
  ['se', '色'],
  ['shan', '山删闪'],
  ['shang', '上商'],
  ['she', '设社射'],
  ['shen', '深审申'],
  ['sheng', '生省升胜'],
  ['shi', '是时实式试市识'],
  ['shou', '首手受'],
  ['shu', '数书输属术'],
  ['shuang', '双'],
  ['shui', '水'],
  ['si', '私四司'],
  ['song', '送松'],
  ['su', '速苏'],
  ['suan', '算'],
  ['tai', '台态'],
  ['tan', '探弹'],
  ['tang', '堂唐'],
  ['tao', '套桃'],
  ['te', '特'],
  ['ti', '体提题替'],
  ['tian', '天填'],
  ['tong', '通同统桶'],
  ['tou', '投头'],
  ['tu', '图土'],
  ['tui', '推退'],
  ['wa', '瓦'],
  ['wai', '外'],
  ['wan', '万完网'],
  ['wei', '维为位微未卫'],
  ['wen', '文稳问'],
  ['wo', '我'],
  ['wu', '务物无五武'],
  ['xi', '西息系析细习'],
  ['xia', '下夏'],
  ['xian', '线先显限现'],
  ['xiang', '向项箱详'],
  ['xiao', '小效消'],
  ['xin', '新信心'],
  ['xing', '型星行性姓形'],
  ['xiu', '修休'],
  ['xu', '虚需续序'],
  ['xuan', '选宣'],
  ['ya', '压亚'],
  ['yan', '验研盐严'],
  ['yang', '阳样'],
  ['yao', '要钥'],
  ['ye', '业页夜'],
  ['yi', '一已以移易仪'],
  ['yin', '音银引隐'],
  ['ying', '应营影硬'],
  ['yong', '用永'],
  ['you', '有友邮右'],
  ['yu', '域预云运语'],
  ['yuan', '源原远员'],
  ['yue', '月越'],
  ['yun', '云运'],
  ['zai', '载在再'],
  ['zan', '暂'],
  ['zao', '造早'],
  ['ze', '则责'],
  ['zeng', '增'],
  ['zha', '查闸'],
  ['zhai', '摘宅'],
  ['zhan', '站占展'],
  ['zhang', '章账张'],
  ['zhao', '找招照'],
  ['zhe', '浙者'],
  ['zhen', '真针镇'],
  ['zheng', '正证整'],
  ['zhi', '支直指制智'],
  ['zhong', '中终重'],
  ['zhou', '州周'],
  ['zhu', '主注助驻'],
  ['zhuan', '专转'],
  ['zhun', '准'],
  ['zi', '资子自字'],
  ['zong', '总'],
  ['zu', '组租'],
  ['zuo', '作左座'],
];

const PINYIN_BY_CHAR = new Map<string, string>();

PINYIN_GROUPS.forEach(([pinyin, chars]) => {
  Array.from(chars).forEach((char) => {
    PINYIN_BY_CHAR.set(char, pinyin);
  });
});

const isAsciiSearchChar = (char: string): boolean => /^[a-z0-9]$/i.test(char);

/**
 * Builds romanized search aliases for mixed Chinese and ASCII labels.
 *
 * @param value - Raw field text from a connection or tag.
 * @returns Deduplicated aliases containing full pinyin and initials.
 */
export const createPinyinSearchTerms = (value: string | null | undefined): string[] => {
  const source = (value ?? '').trim().toLowerCase();
  if (!source) {
    return [];
  }

  const fullParts: string[] = [];
  const initialParts: string[] = [];
  let hasPinyin = false;

  Array.from(source).forEach((char) => {
    const pinyin = PINYIN_BY_CHAR.get(char);
    if (pinyin) {
      fullParts.push(pinyin);
      initialParts.push(pinyin[0]);
      hasPinyin = true;
      return;
    }

    if (isAsciiSearchChar(char)) {
      fullParts.push(char);
      initialParts.push(char);
    }
  });

  if (!hasPinyin) {
    return [];
  }

  return Array.from(new Set([
    fullParts.join(''),
    initialParts.join(''),
  ].filter(Boolean)));
};
